theme = "catppuchin/mocha"
gutter = "relative"

[keymap.default] # Default keymap for the editor
"q" = { type = "Quit" }
"<Esc>" = { type = "EnterMode", params = { mode = "Normal" } }

[keymap.movement] # Movement keymap for the editor
"h" = { type = "MoveLeft", params = { inline = true } }
"j" = { type = "MoveDown" }
"k" = { type = "MoveUp" }
"l" = { type = "MoveRight", params = { inline = true } }

"<Left>" = { type = "MoveLeft", params = { inline = true } }
"<Right>" = { type = "MoveRight", params = { inline = true } }
"<Up>" = { type = "MoveUp" }
"<Down>" = { type = "MoveDown" }

"<Backspace>" = { type = "MoveLeft", params = { inline = false } }

"$" = { type = "MoveToLineEnd" }
"0" = { type = "MoveToLineStart" }

"w" = { type = "MoveToNextWord" }
"b" = { type = "MoveToPreviousWord" }

"<Home>" = { type = "MoveToLineStart" }
"<End>" = { type = "MoveToLineEnd" }

[keymap.normal] # Keymode for normal mode only
"gg" = { type = "MoveToTop" }
"G" = { type = "MoveToBottom" }
"zz" = { type = "MoveToViewportCenter" }

"x" = { type = "DeleteChar", params = { inline = true } }
"X" = { type = "Backspace", params = { inline = true } }
"d" = { type = "EnterMode", params = { mode = { OperationPending = "Delete" } } }
"c" = { type = "EnterMode", params = { mode = { OperationPending = "Change" } } }

"i" = { type = "EnterMode", params = { mode = "Insert" } }
":" = { type = "EnterMode", params = { mode = "Command" } }
"/" = { type = "EnterMode", params = { mode = "Search" } }

"n" = { type = "FindNext" }
"N" = { type = "FindPrevious" }

"u" = { type = "Undo" }
"<CONTROL-r>" = { type = "Redo" }

"gd" = { type = "GoToDefinition" }

"a" = { type = "Composite", params = { description = "Insert after the cursor", actions = [
    { type = "EnterMode", params = { mode = "Insert" } },
    { type = "MoveRight", params = { inline = false } }
] } }

"A" = { type = "Composite", params = { description = "Insert at the end of the line", actions = [
    { type = "EnterMode", params = { mode = "Insert" } },
    { type = "MoveToLineEnd" }
] } }

"o" = { type = "Composite", params = { description = "Insert new line below the current line", actions = [
    { type = "InsertNewLineBelow" },
    { type = "EnterMode", params = { mode = "Insert" } }
] } }

"O" = { type = "Composite", params = { description = "Insert new line above the current line", actions = [
    { type = "InsertNewLineAbove" },
    { type = "EnterMode", params = { mode = "Insert" } }
] } }

[keymap.pending.delete]
"d" = { type = "DeleteCurrentLine" }

[keymap.pending.change]
"c" = { type = "ChangeCurrentLine" }