theme = "themes/catppuchin/mocha.json"
tab_size = 4
log_file = "/tmp/viron.log"

[keys.normal]
"w" = "MoveToNextWord"
"b" = "MoveToPreviousWord"
"q" = "Quit"
"u" = "Undo"
"k" = "MoveUp"
"j" = "MoveDown"
"l" = "MoveRight"
"h" = "MoveLeft"
"Up" = "MoveUp"
"Down" = "MoveDown"
"Left" = "MoveLeft"
"Right" = "MoveRight"
"0" = "MoveToLineStart"
"$" = "MoveToLineEnd"
"Home" = "MoveToLineStart"
"End" = "MoveToLineEnd"
"G" = "MoveToBottom"
"o" = [{ EnterMode = "Insert" }, "MoveToLineEnd", "InsertNewLineAtCursor"]
"O" = "InsertNewLineAtCurrentLine"
"x" = "DeleteCharAtCursor"
"Ctrl-b" = "PageUp"
"Ctrl-f" = "PageDown"

"i" = { EnterMode = "Insert" }
"a" = [{ EnterMode = "Insert" }, "MoveRight"]

":" = { EnterMode = "Command" }
"/" = { EnterMode = "Search" }
"n" = "FindNext"
"N" = "FindPrevious"

[keys.normal.g]
"g" = "MoveToTop"
"d" = "GotoDefinition"

[keys.normal.d]
"d" = "DeleteCurrentLine"
"w" = "DeleteWord"

[keys.normal.z]
"z" = "MoveToViewportCenter"

[keys.insert]
"Esc" = { EnterMode = "Normal" }
"Up" = "MoveUp"
"Down" = "MoveDown"
"Left" = "MoveLeft"
"Right" = "MoveRight"
"Delete" = "DeleteCharAtCursor"
"Backspace" = "BackspaceCharAtCursor"
"Enter" = "InsertNewLineAtCursor"
"Tab" = "InsertTabAtCursor"

[keys.command]
"Esc" = { EnterMode = "Normal" }
"Left" = "MoveLeft"
"Right" = "MoveRight"
"Backspace" = "BackspaceCharAtCursor"
"Enter" = "ExecuteCommand"
