theme = "themes/catppuchin/mocha.json"

[keys.normal]
"q" = "Quit"
"u" = "Undo"
"k" = "MoveUp"
"j" = "MoveDown"
"l" = "MoveRight"
"h" = "MoveLeft"
"Up" = "MoveUp"
"Down" = "MoveDown"
"Left" = "MoveLeft"
"Right" = "MoveRight"
"0" = "MoveToLineStart"
"$" = "MoveToLineEnd"
"Home" = "MoveToLineStart"
"End" = "MoveToLineEnd"
"G" = "MoveToBottom"
"o" = [{ EnterMode = "Insert" }, "MoveToLineEnd", "NewLineAtCursor"]
"O" = [{ EnterMode = "Insert" }, "MoveToLineStart", "NewLineAtCursor", "MoveUp"]
"x" = "DeleteCharAtCursor"
"Ctrl-b" = "PageUp"
"Ctrl-f" = "PageDown"

"i" = { EnterMode = "Insert" }
"a" = [{ EnterMode = "Insert" }, "MoveRight"]

[keys.normal.g]
"g" = "MoveToTop"

[keys.normal.d]
"d" = "DeleteCurrentLine"

[keys.normal.z]
"z" = "MoveToViewportCenter"

[keys.insert]
"Esc" = { EnterMode = "Normal" }
"Up" = "MoveUp"
"Down" = "MoveDown"
"Left" = "MoveLeft"
"Right" = "MoveRight"
"Delete" = "DeleteCharAtCursor"
"Backspace" = "BackspaceCharAtCursor"
"Enter" = "NewLineAtCursor"
