theme = "themes/catppuchin/mocha.json"

# Keybindings for normal mode
[keymap.normal]
"q" = { type = "Quit" }
"<Esc>" = { type = "EnterMode", params = { mode = "normal" } }

"h" = { type = "MoveLeft", params = { count = 1 } }
"j" = { type = "MoveDown", params = { count = 1 } }
"k" = { type = "MoveUp", params = { count = 1 } }
"l" = { type = "MoveRight", params = { count = 1 } }
"<Left>" = { type = "MoveLeft", params = { count = 1 } }
"<Right>" = { type = "MoveRight", params = { count = 1 } }
"<Up>" = { type = "MoveUp", params = { count = 1 } }
"<Down>" = { type = "MoveDown", params = { count = 1 } }

"$" = { type = "MoveToLineEnd" }
"0" = { type = "MoveToLineStart" }
"<Home>" = { type = "MoveToLineStart" }
"<End>" = { type = "MoveToLineEnd" }
"gg" = { type = "MoveToTop" }
"G" = { type = "MoveToBottom" }
"zz" = { type = "MoveToViewportCenter" }

"w" = { type = "MoveToNextWord" }
"b" = { type = "MoveToPreviousWord" }

"x" = { type = "DeleteChar" }

"i" = { type = "EnterMode", params = { mode = "insert" } }
":" = { type = "EnterMode", params = { mode = "command" } }
"/" = { type = "EnterMode", params = { mode = "search" } }

"n" = { type = "FindNext" }
"N" = { type = "FindPrevious" }

"u" = { type = "UndoBuffer" }
"<CONTROL-r>" = { type = "RedoBuffer" }

"gd" = { type = "GoToDefinition" }

[keymap.normal.a]
type = "Composite"
params = { description = "Insert mode with move right", actions = [
    { type = "EnterMode", params = { mode = "insert" } },
    { type = "MoveRight", params = { count = 1 } }
] }

[keymap.normal.A]
type = "Composite"
params = { description = "Insert mode at line end", actions = [
    { type = "EnterMode", params = { mode = "insert" } },
    { type = "MoveToLineEnd" }
] }

[keymap.normal.o]
type = "Composite"
params = { description = "Insert new line at cursor", actions = [
    { type = "InsertNewLineBelow" },
    { type = "EnterMode", params = { mode = "insert" } }
] }

[keymap.normal.O]
type = "Composite"
params = { description = "Insert new line at current line", actions = [
    { type = "InsertNewLineAbove" },
    { type = "EnterMode", params = { mode = "insert" } }
] }

# Keybindings for insert mode
[keymap.insert]
"<Esc>" = { type = "EnterMode", params = { mode = "normal" } }
"<Delete>" = { type = "DeleteChar" }
"<Backspace>" = { type = "Backspace" }
"<Enter>" = { type = "InsertNewLine" }
"<Left>" = { type = "MoveLeft", params = { count = 1 } }
"<Right>" = { type = "MoveRight", params = { count = 1 } }
"<Up>" = { type = "MoveUp", params = { count = 1 } }
"<Down>" = { type = "MoveDown", params = { count = 1 } }
"<Home>" = { type = "MoveToLineStart" }
"<End>" = { type = "MoveToLineEnd" }

[keymap.command]
"<Esc>" = { type = "EnterMode", params = { mode = "normal" } }

[keymap.search]
"<Esc>" = { type = "EnterMode", params = { mode = "normal" } }